swagger: '2.0'
info:
  title:  api-gateway-to-vm
  description: API Gateway to VM
  version: 1.0.0
schemes:
  - https
paths:
  /:
    get:
      summary: Post method
      operationId: post
      x-google-backend:
        address: https://35.226.201.63:8080
      responses:
        '200':
          description: A successful response
          schema:
            type: string
