data:
  support_dir: "support_images"
  query_dir: "query_images"
  output_dir: "results"
  format: "jpg"

labeling:
  mask: 1
  polygon: 1
  bounding_box: 1
  polygon_resolution: 0.01
  number_of_local_max: 5

window_size: [1024, 1024]
model: vit_h # Faster <<< vit_b, vit_l, vit_h >>> More accurate
threshold: 0.5
device: "cuda"
COLORMAP: [[255, 0, 121],[101, 0, 255],[253, 255, 0],[0, 49, 255],[0, 186, 255],[0, 255, 39],[215, 0, 255],[0, 24, 255],[0, 157, 255],[0, 131, 255]]

