name: Build and Push Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(cat version.txt)"

    - name: Login to Google Cloud Registry
      uses: docker/login-action@v1 
      with:
        registry: europe-west4-docker.pkg.dev/few-shot-sam/fsm-artifact-docker/few_shot_sam_backend
        username: _json_key
        password: ${{ secrets.GCP_ARTIFACT_REGISTRY_WRITER }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: europe-west4-docker.pkg.dev/few-shot-sam/fsm-artifact-docker/few_shot_sam_backend:${{ steps.version.outputs.version }}

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Google Cloud Registry
      uses: docker/login-action@v1 
      with:
        registry: europe-west4-docker.pkg.dev/few-shot-sam/fsm-artifact-docker/few_shot_sam_backend
        username: _json_key
        password: ${{ secrets.GCP_ARTIFACT_REGISTRY_WRITER }}

    - name: Pull and run Docker image
      run: |
        docker pull europe-west4-docker.pkg.dev/few-shot-sam/fsm-artifact-docker/few_shot_sam_backend:${{ needs.build.outputs.version }}
        docker run europe-west4-docker.pkg.dev/few-shot-sam/fsm-artifact-docker/few_shot_sam_backend:${{ needs.build.outputs.version }}
